# --- Serving options --- #
# If you are building a GitHub project page then use these settings:
# url is the full website URL
url: "http://droglenc.github.io/NCMTH107"
# baseurl is the website's URL without the hostname
baseurl: "/NCMTH107"

# Name of website
title: NCMTH107

# Short description of your site
description: Introductory Statistics at Northland College.

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
#avatar: "/img/fishRlogoSquareWhite.png"

# List of links in the navigation bar
navbar-links:
  fishr: "derekogle.com/fishR/"
  Book: ""
  Lecture: ""
  Resources: ""
  Syllabus: ""
  Derek: ""
  Home: ""

# --- Footer options --- #
author:
  name: Derek H. Ogle
  email: "dogle@northland.edu"

# Select which links to show in the footer
footer-links-active:
  email: true
  github: false
  twitter: false
  facebook: false
  rss: false
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
url-pretty: "derekogle.com/NCMTH107/"

# --- Pagination options --- #
paginate: 6

# --- Don't need to touch anything below here (but you can if you want) --- #
# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: pygments
permalink: /:year-:month-:day-:title

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# prose.io options
prose:
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - /_includes
    - /_layouts
    - /css
    - /img
    - /js
